-- Crear la base de datos
CREATE DATABASE VRWorld;

-- Seleccionar la base de datos
USE VRWorld;

-- Crear la tabla USUARIO
CREATE TABLE USUARIO (
    DNI VARCHAR(20) PRIMARY KEY,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    Edad INT,
    Nombre VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Crear la tabla TURISTA
CREATE TABLE TURISTA (
    DNI VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (DNI) REFERENCES USUARIO(DNI),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Crear la tabla GUIA
CREATE TABLE GUIA (
    DNI VARCHAR(20) PRIMARY KEY,
    Salario DECIMAL(10, 2),
    FOREIGN KEY (DNI) REFERENCES USUARIO(DNI),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Crear la tabla ESP
CREATE TABLE ESP (
    DNI VARCHAR(20),
    esp ENUM('Bosque', 'Museo', 'Ruinas', 'Playas', 'Montañas'),
    PRIMARY KEY (DNI, esp),
    FOREIGN KEY (DNI) REFERENCES GUIA(DNI),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Crear la tabla TOUR
CREATE TABLE TOUR (
    ID INT PRIMARY KEY,
    Pais VARCHAR(100),
    Tipo ENUM('Bosque', 'Museo', 'Ruinas', 'Playas', 'Montañas'),
    Precio DECIMAL(10, 2),
    Duracion INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Crear la tabla GUIA_TOUR
CREATE TABLE GUIA_TOUR (
    DNI VARCHAR(20),
    ID INT,
    PRIMARY KEY (DNI, ID),
    FOREIGN KEY (DNI) REFERENCES GUIA(DNI),
    FOREIGN KEY (ID) REFERENCES TOUR(ID),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Crear la tabla FACTURA
CREATE TABLE FACTURA (
    ID INT PRIMARY KEY,
    MetodoPago VARCHAR(50),
    Fecha DATE,
    ImporteTotal DECIMAL(10, 2),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Crear la tabla ALQUILER
CREATE TABLE ALQUILER (
    DNI VARCHAR(20),
    TourID INT,
    FacturaID INT not null,
    PRIMARY KEY (DNI, TourID),
    FOREIGN KEY (DNI) REFERENCES TURISTA(DNI),
    FOREIGN KEY (TourID) REFERENCES TOUR(ID),
    FOREIGN KEY (FacturaID) REFERENCES FACTURA(ID),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

